
var strings = [
	{name : "app_name", string : "Sky Map"},
	{name : "menu_settings", string : "Settings"},
	{name : "menu_search", string : "Search"},
	{name : "cancel", string : "Cancel"},
	{name : "set", string : "Set"},
	{name : "go", string : "Go!"},
	{name : "location_prefs", string : "Location Settings"},
	{name : "force_gps_pref", string : "Always use GPS"},
	{name : "force_gps_pref_hint" , string : "if enabled, even if network location is available"},
	{name : "no_use_gps_pref", string : "Set location manually"},
	{name : "no_use_gps_pref_hint", string : "Enter a place or a lat/long below"},
	{name : "location_placename", string : "Place name"},
	{name : "location_placename_hint", string : "e.g. 1400 West Mars Hill Road, Flagstaff, AZ."},
	{name : "location_lat_pref", string : "Latitude"},
	{name : "location_long_pref", string : "Longitude"},
	{name : "degrees", string : "Degrees"},
	{name : "preferences", string : "preferences"},
	{name : "location_no_auto", string : "Your phone does not support auto-location.   You can set the location manually in preferences."},
	{name : "location_offer_to_enable", string : "Auto-location is disabled.  Would you like to enable it?"},
	{name : "location_offer_to_enable_gps_title", string : "Auto-location disabled"},
	{name : "location_set_auto", string : "Location set from %1$s to %2$s"},
	{name : "location_unable_to_geocode", string : "Unable to decode your location - perhaps your network isn\'t available?"},
	{name : "location_not_found_title" , string : "Sorry"},
	{name : "location_not_found" , string : "%s not found."},
	{name : "location_long_lat", string : "Longitude:%1$s, Latitude:%2$s"},
	{name : "location_place_found", string : "Place found.  Setting latitude %1$f and longitude %2$f"},
	{name : "use_magnetic_correction", string : "Use magnetic correction"},
	{name : "use_magnetic_correction_hint", string : "Use knowledge of your location to correct orientation from magnetic north to true north"},<!-- This string is too long and currently unused --, string : "
	{name : "provider_prefs", string : "Show..."},
	{name : "show_stars_pref", string : "Stars"},
	{name : "show_constellations_pref", string : "Constellations"},
	{name : "show_messier_objects_pref", string : "Messier Objects"},
	{name : "show_planets_pref", string : "Planets"},
	{name : "show_grid_pref", string : "RA/Dec Grid"},
	{name : "show_horizon_pref", string : "Horizon"},
	{name : "show_sky_gradient", string : "Sky Gradient"},
	{name : "show_meteors_pref", string : "Meteor Showers"},
	{name : "sensor_prefs", string : "Sensor Settings"},
	{name : "sensor_speed", string : "Sensor Speed"},
	{name : "sensor_damping", string : "Damping"},
	{name : "ecliptic", string : "Ecliptic"},
	{name : "show_hubble_layer_pref", string : "Hubble Images"},
	{name : "malformed_loc_error", string : "Latitude or longitude setting isn\'t a number."},
	{name : "dialog_accept" , string : "Accept"},
	{name : "dialog_decline", string : "No Thanks"},
	{name : "menu_help" , string : "Help"},
	{name : "help_dialog_title", string : "Help for Sky Map"},
	{name : "eula_dialog_title", string : "End User License Agreement"},
	{name : "set_manual", string : "Switching to manual mode"},
	{name : "set_auto", string : "Switching to automatic mode"},
	{name : "menu_zoom_in", string : "Zoom in"},
	{name : "menu_zoom_out", string : "Zoom out"},
	{name : "menu_toggle_dim", string : "Toggle night mode"},
	{name : "zenith", string : "ZENITH"},
	{name : "nadir", string : "NADIR"},
	{name : "north", string : "NORTH"},
	{name : "east", string : "EAST"},
	{name : "west", string : "WEST"},
	{name : "south", string : "SOUTH"},
	{name : "search_label", string : "Search the Sky"},
	{name : "search_hint" , string : "e.g. Mars"},
	{name : "no_search_title", string : "No results"},
	{name : "no_search_results_text", string : "No results were found."},
	{name : "many_search_results_title", string : "Did you mean?"},
	{name : "many_search_results_text", string : "Please select one"},
	{name : "searching_for_text", string : "Searching for %s..."},
	{name : "found_target_text", string : "Found %s."},
	{name : "other", string : "Other"},
	{name : "planetary_images", string : "Show Planet Images"},
	{name : "menu_time" , string : "Time Travel"},
	{name : "time_travel_start_message" , string : "Traveling through time ..."},
	{name : "time_travel_start_message_alt" , string : "Traveling through time to %s ..."},
	{name : "time_travel_close_message" , string : "Back to the present ..."},
	{name : "popular_dates_prompt", string : "Popular dates"},
	{name : "custom_date_prompt", string : "Or select your own date"},
	{name : "change_date_prompt" , string : "Change the date"},
	{name : "change_time_prompt" , string : "Change the time"},
	{name : "now_visiting", string : "Now visiting: %s"},
	{name : "time_travel_label_past", string : "Time Travel: Past"},
	{name : "time_travel_label_future", string : "Time Travel: Future"},
	{name : "time_travel_stopped", string : "Time travel frozen"},
	{name : "time_travel_second_speed", string : "Traveling &gt; @ 1 sec/sec"},
	{name : "time_travel_minute_speed", string : "Traveling &gt; @ 1 min/sec"},
	{name : "time_travel_10minute_speed", string : "Traveling &gt; @ 10 min/sec"},
	{name : "time_travel_hour_speed", string : "Traveling &gt; @ 1 hour/sec"},
	{name : "time_travel_day_speed", string : "Traveling &gt; @ 1 day/sec"},
	{name : "time_travel_week_speed", string : "Traveling &gt; @ 1 week/sec"},
	{name : "time_travel_second_speed_back", string : "Traveling &lt; @ 1 sec/sec"},
	{name : "time_travel_minute_speed_back", string : "Traveling &lt; @ 1 min/sec"},
	{name : "time_travel_10minute_speed_back", string : "Traveling &lt; @ 10 min/sec"},
	{name : "time_travel_hour_speed_back", string : "Traveling &lt; @ 1 hour/sec"},
	{name : "time_travel_day_speed_back", string : "Traveling &lt; @ 1 day/sec"},
	{name : "time_travel_week_speed_back", string : "Traveling &lt; @ 1 week/sec"},
	{name : "use_sound_effects", string : "Enable sound"},
	{name : "enable_layer_toast", string : "Enabling %s layer"},
	{name : "disable_layer_toast", string : "Disabling %s layer"},
	{name : "menu_gallery", string : "Gallery"},
	{name : "gallery_image_search_btn", string : "Find in sky"},
	{name : "gallery_image_back_btn", string : "Back to gallery"},
	{name : "hubble_image_gallery_title", string : "Sky Map Hubble Gallery"},
	{name : "hubble_image", string : "Hubble Image"},<!--  TODO(johntaylor): currently unused --, string : "
	{name : "search_target_found_message", string : "You found:"},
	{name : "search_overlay_title", string : "Point your phone toward the arrow"},
	{name : "search_target_looking_message", string : "Looking for:"},
	{name : "sun_wont_set_message", string : "The sun will not set during the next 24 hours at your current location."},
	{name : "sun_wont_rise_message", string : "The sun will not rise during the next 24 hours at your current location."},
	{name : "sun", string : "Sun"},
	{name : "moon", string : "Moon"},
	{name : "mercury", string : "Mercury"},
	{name : "venus", string : "Venus"},
	{name : "earth", string : "Earth"},
	{name : "mars", string : "Mars"},
	{name : "jupiter", string : "Jupiter"},
	{name : "saturn", string : "Saturn"},
	{name : "uranus", string : "Uranus"},
	{name : "neptune", string : "Neptune"},
	{name : "pluto", string : "Pluto"},
	{name : "crab_nebula", string : "Crab Nebula"},
	{name : "eagle_nebula", string : "Eagle Nebula"},
	{name : "andromeda_galaxy", string : "Andromeda Galaxy"},
	{name : "orion_nebula", string : "Orion Nebula"},
	{name : "whirlpool_galaxy", string : "Whirlpool Galaxy"},
	{name : "ring_nebula", string : "Ring Nebula"},
	{name : "pinwheel_galaxy", string : "Pinwheel Galaxy"},
	{name : "sombrero_galaxy", string : "Sombrero Galaxy"},
	{name : "hercules_gc", string : "Hercules Globular Cluster"},
	{name : "pleiades", string : "Pleiades"},
	{name : "cats_eye_nebula", string : "Cat\'s Eye Nebula"},
	{name : "omega_centauri", string : "Omega Centauri Globular Cluster"},
	{name : "v838_mon", string : "V838 Monocerotis"},
	{name : "sn1987a", string : "Supernova 1987a"},
	{name : "hubble_deep_field", string : "Hubble Deep Field"},
	{name : "rho_oph", string : "Rho Ophiuchus"},
	{name : "menu_tos", string : "Terms of Service"},
	{name : "control_panel_btn", string : "Control Panel"},
	{name : "allow_rotation_pref", string : "Multitouch rotation"},
	{name : "allow_rotation_pref_desc", string : "if supported by the phone"},
	{name : "north_pole", string : "NP"},
	{name : "south_pole", string : "SP"},
	{name : "andromeda", string : "Andromeda"},
	{name : "aquarius", string : "Aquarius"},
	{name : "aquila", string : "Aquila"},
	{name : "aries", string : "Aries"},
	{name : "auriga", string : "Auriga"},
	{name : "bootes", string : "Bootes"},
	{name : "cancer", string : "Cancer"},
	{name : "canis_major", string : "Canis Major"},
	{name : "capricornus", string : "Capricornus"},
	{name : "carina", string : "Carina"},
	{name : "cassiopeia", string : "Cassiopeia"},
	{name : "centaurus", string : "Centaurus"},
	{name : "cetus", string : "Cetus"},
	{name : "crux", string : "Crux"},
	{name : "cygnus", string : "Cygnus"},
	{name : "draco", string : "Draco"},
	{name : "eridanus", string : "Eridanus"},
	{name : "gemini", string : "Gemini"},
	{name : "grus", string : "Grus"},
	{name : "hercules", string : "Hercules"},
	{name : "hydrus", string : "Hydrus"},
	{name : "leo", string : "Leo"},
	{name : "libra", string : "Libra"},
	{name : "lupus", string : "Lupus"},
	{name : "lyra", string : "Lyra"},
	{name : "ophiuchus", string : "Ophiuchus"},
	{name : "orion", string : "Orion"},
	{name : "pavo", string : "Pavo"},
	{name : "pegasus", string : "Pegasus"},
	{name : "perseus", string : "Perseus"},
	{name : "phoenix", string : "Phoenix"},
	{name : "pisces", string : "Pisces"},
	{name : "piscis_austrinus", string : "Piscis Austrinus"},
	{name : "puppis", string : "Puppis"},
	{name : "sagittarius", string : "Sagittarius"},
	{name : "scorpius", string : "Scorpius"},
	{name : "taurus", string : "Taurus"},
	{name : "tucana", string : "Tucana"},
	{name : "ursa_major", string : "Ursa Major"},
	{name : "ursa_minor", string : "Ursa Minor"},
	{name : "vela", string : "Vela"},
	{name : "virgo", string : "Virgo"},
	{name : "capricorn", string : "Capricorn"},
	{name : "southern_cross", string : "Southern Cross"},
	{name : "scorpio", string : "Scorpio"},
	{name : "little_dipper", string : "Little Dipper"},
	{name : "little_bear", string : "Little Bear"},
	{name : "big_dipper", string : "Big Dipper"},
	{name : "great_bear", string : "Great Bear"},
	{name : "plough", string : "Plough"},
	{name : "sirius", string : "Sirius"},
	{name : "canopus", string : "Canopus"},
	{name : "arcturus", string : "Arcturus"},
	{name : "rigel_kentaurus_a", string : "Rigel Kentaurus A"},
	{name : "vega", string : "Vega"},
	{name : "rigel", string : "Rigel"},
	{name : "procyon", string : "Procyon"},
	{name : "betelgeuse", string : "Betelgeuse"},
	{name : "achernar", string : "Achernar"},
	{name : "hadar", string : "Hadar"},
	{name : "capella", string : "Capella"},
	{name : "altair", string : "Altair"},
	{name : "acrux", string : "Acrux"},
	{name : "aldebaran", string : "Aldebaran"},
	{name : "spica", string : "Spica"},
	{name : "antares", string : "Antares"},
	{name : "pollux", string : "Pollux"},
	{name : "fomalhaut", string : "Fomalhaut"},
	{name : "deneb", string : "Deneb"},
	{name : "regulus", string : "Regulus"},
	{name : "adhara", string : "Adhara"},
	{name : "shaula", string : "Shaula"},
	{name : "alnath", string : "Alnath"},
	{name : "alnilam", string : "Alnilam"},
	{name : "alnair", string : "Alnair"},
	{name : "alioth", string : "Alioth"},
	{name : "mirphak", string : "Mirphak"},
	{name : "kaus_australis", string : "Kaus Australis"},
	{name : "dubhe", string : "Dubhe"},
	{name : "alkaid", string : "Alkaid"},
	{name : "alhena", string : "Alhena"},
	{name : "castor", string : "Castor"},
	{name : "polaris", string : "Polaris"},
	{name : "alphard", string : "Alphard"},
	{name : "hamal", string : "Hamal"},
	{name : "algieba", string : "Algieba"},
	{name : "diphda", string : "Diphda"},
	{name : "nunki", string : "Nunki"},
	{name : "mirach", string : "Mirach"},
	{name : "alpheratz", string : "Alpheratz"},
	{name : "saiph", string : "Saiph"},
	{name : "kochab", string : "Kochab"},
	{name : "rasalhague", string : "Rasalhague"},
	{name : "algol", string : "Algol"},
	{name : "denebola", string : "Denebola"},
	{name : "alphekka", string : "Alphekka"},
	{name : "etamin", string : "Etamin"},
	{name : "kaus", string : "Kaus"},
	{name : "shedir", string : "Shedir"},
	{name : "caph", string : "Caph"},
	{name : "izar", string : "Izar"},
	{name : "merak", string : "Merak"},
	{name : "enif", string : "Enif"},
	{name : "ankaa", string : "Ankaa"},
	{name : "phad", string : "Phad"},
	{name : "alderamin", string : "Alderamin"},
	{name : "scheat", string : "Scheat"},
	{name : "markab", string : "Markab"},
	{name : "menkar", string : "Menkar"},
	{name : "arneb", string : "Arneb"},
	{name : "unukalhai", string : "Unukalhai"},
	{name : "algenib", string : "Algenib"},
	{name : "vindemiatrix", string : "Vindemiatrix"},
	{name : "alcyone", string : "Alcyone"},
	{name : "dog_star", string : "Dog Star"},
	{name : "north_star", string : "North Star"},
	{name : "pole_star", string : "Pole Star"},
	{name : "m1", string : "M1"},
	{name : "m2", string : "M2"},
	{name : "m3", string : "M3"},
	{name : "m4", string : "M4"},
	{name : "m5", string : "M5"},
	{name : "m6", string : "M6"},
	{name : "m7", string : "M7"},
	{name : "m8", string : "M8"},
	{name : "m9", string : "M9"},
	{name : "m10", string : "M10"},
	{name : "m11", string : "M11"},
	{name : "m12", string : "M12"},
	{name : "m13", string : "M13"},
	{name : "m14", string : "M14"},
	{name : "m15", string : "M15"},
	{name : "m16", string : "M16"},
	{name : "m17", string : "M17"},
	{name : "m18", string : "M18"},
	{name : "m19", string : "M19"},
	{name : "m20", string : "M20"},
	{name : "m21", string : "M21"},
	{name : "m22", string : "M22"},
	{name : "m23", string : "M23"},
	{name : "m24", string : "M24"},
	{name : "m25", string : "M25"},
	{name : "m26", string : "M26"},
	{name : "m27", string : "M27"},
	{name : "m28", string : "M28"},
	{name : "m29", string : "M29"},
	{name : "m30", string : "M30"},
	{name : "m31", string : "M31"},
	{name : "m32", string : "M32"},
	{name : "m33", string : "M33"},
	{name : "m34", string : "M34"},
	{name : "m35", string : "M35"},
	{name : "m36", string : "M36"},
	{name : "m37", string : "M37"},
	{name : "m38", string : "M38"},
	{name : "m39", string : "M39"},
	{name : "m40", string : "M40"},
	{name : "m41", string : "M41"},
	{name : "m42", string : "M42"},
	{name : "m43", string : "M43"},
	{name : "m44", string : "M44"},
	{name : "m45", string : "M45"},
	{name : "m46", string : "M46"},
	{name : "m47", string : "M47"},
	{name : "m48", string : "M48"},
	{name : "m49", string : "M49"},
	{name : "m50", string : "M50"},
	{name : "m51", string : "M51"},
	{name : "m52", string : "M52"},
	{name : "m53", string : "M53"},
	{name : "m54", string : "M54"},
	{name : "m55", string : "M55"},
	{name : "m56", string : "M56"},
	{name : "m57", string : "M57"},
	{name : "m58", string : "M58"},
	{name : "m59", string : "M59"},
	{name : "m60", string : "M60"},
	{name : "m61", string : "M61"},
	{name : "m62", string : "M62"},
	{name : "m63", string : "M63"},
	{name : "m64", string : "M64"},
	{name : "m65", string : "M65"},
	{name : "m66", string : "M66"},
	{name : "m67", string : "M67"},
	{name : "m68", string : "M68"},
	{name : "m69", string : "M69"},
	{name : "m70", string : "M70"},
	{name : "m71", string : "M71"},
	{name : "m72", string : "M72"},
	{name : "m73", string : "M73"},
	{name : "m74", string : "M74"},
	{name : "m75", string : "M75"},
	{name : "m76", string : "M76"},
	{name : "m77", string : "M77"},
	{name : "m78", string : "M78"},
	{name : "m79", string : "M79"},
	{name : "m80", string : "M80"},
	{name : "m81", string : "M81"},
	{name : "m82", string : "M82"},
	{name : "m83", string : "M83"},
	{name : "m84", string : "M84"},
	{name : "m85", string : "M85"},
	{name : "m86", string : "M86"},
	{name : "m87", string : "M87"},
	{name : "m88", string : "M88"},
	{name : "m89", string : "M89"},
	{name : "m90", string : "M90"},
	{name : "m91", string : "M91"},
	{name : "m92", string : "M92"},
	{name : "m93", string : "M93"},
	{name : "m94", string : "M94"},
	{name : "m95", string : "M95"},
	{name : "m96", string : "M96"},
	{name : "m97", string : "M97"},
	{name : "m98", string : "M98"},
	{name : "m99", string : "M99"},
	{name : "m100", string : "M100"},
	{name : "m101", string : "M101"},
	{name : "m102", string : "M102"},
	{name : "m103", string : "M103"},
	{name : "m104", string : "M104"},
	{name : "m105", string : "M105"},
	{name : "m106", string : "M106"},
	{name : "m107", string : "M107"},
	{name : "m108", string : "M108"},
	{name : "m109", string : "M109"},
	{name : "m110", string : "M110"},
	{name : "ngc6543", string : "NGC6543"},
	{name : "ngc5139", string : "NGC5139"},
	{name : "butterfly_cluster", string : "Butterfly Cluster"},
	{name : "scorpions_tail", string : "Scorpion\'s Tail"},
	{name : "winnecke_4", string : "Winnecke 4"},
	{name : "beehive_cluster", string : "Beehive Cluster"},
	{name : "praesepe", string : "Praesepe"},
	{name : "seven_sisters", string : "Seven Sisters"},
	{name : "space_station", string : "International Space Station"},
	{name : "space_shuttle", string : "Space Shuttle"},
	{name : "kml_load_error", string : "Failed to load KML file"},
	{name : "load_kml_dialog_title", string : "Load KML"},
	{name : "load_kml_file", string : "Load"},
	{name : "enable_analytics", string : "Send usage statistics"},
	{name : "enable_analytics_desc", string : "Make Sky Map better by sending anonymous data to Google Analytics"},
	{name : "leonids", string : "Leonids"},
	{name : "geminids", string : "Geminids"},
	{name : "quadrantids", string : "Quadrantids"},
	{name : "lyrids", string : "Lyrids"},
	{name : "aquariids", string : "Eta Aquariids"},
	{name : "deltaaquariids", string : "Delta Aquariids"},
	{name : "perseids", string : "Perseids"},
	{name : "orionids", string : "Orionids"},
	{name : "puppidvelids", string : "Puppid-Velids"},
	{name : "ursids", string : "Ursids"},
];
