var TimeConstants = {};

TimeConstants.MILLISECONDS_PER_SECOND =    1000;
TimeConstants.MILLISECONDS_PER_MINUTE =   60000;
TimeConstants.MILLISECONDS_PER_HOUR =   3600000;
TimeConstants.MILLISECONDS_PER_DAY =   86400000;
TimeConstants.MILLISECONDS_PER_WEEK = 604800000;
TimeConstants.SECONDS_PER_SECOND = 1;
TimeConstants.SECONDS_PER_MINUTE = 60;
TimeConstants.SECONDS_PER_10MINUTE = 600;
TimeConstants.SECONDS_PER_HOUR = 3600;
TimeConstants.SECONDS_PER_DAY = 24 * TimeConstants.SECONDS_PER_HOUR;
TimeConstants.SECONDS_PER_WEEK = 7 * TimeConstants.SECONDS_PER_DAY;
TimeConstants.SECONDS_PER_SIDERIAL_DAY = 86164.0905;
TimeConstants.MILLISECONDS_PER_SIDEREAL_DAY =
     TimeConstants. MILLISECONDS_PER_SECOND * TimeConstants.SECONDS_PER_SIDERIAL_DAY;
TimeConstants.SECONDS_PER_SIDERIAL_WEEK = 7 * 86164.0905;

